Console.WriteLine("Введите x1: ");
Console.Write("x1 = ");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите y1: ");
Console.Write("y1 = ");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите x1: ");
Console.Write("x2 = ");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите x1: ");
Console.Write("y2 = ");
int y2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("a = (" + x1 + ", " + y1 + "), b = (" + x2 + ", " + y2 + ")");
double n = Math.Sqrt(Math.Pow(x2-x1,2) + Math.Pow(y2-y1,2));
Console.Write("n = ");
Console.WriteLine(n);